version: '3.9'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '4000:3000'
    volumes:
      - .:/usr/src/app
    command: air main.go
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5431:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
